Deploy include docker save image

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -68,9 +68,21 @@ jobs:
               echo "$IMAGE_NAME"
             fi;
             docker compose up servicio-unidades -d &&
-            while ! docker images | grep "galileo/unidades" | grep "1.1.0"; do
-              echo "Esperando a que la imagen esté lista..."
+            # Inicializar el contador
+            counter=0
+            max_retries=5
+
+            # Esperar a que la imagen "galileo/servicio-unidades:1.1.0" esté lista
+            while ! docker images | grep -E "^galileo\/servicio-unidades\s+1.1.0"; do
+              echo "Esperando a que la imagen servicio-unidades:1.1.0 esté lista..."
               sleep 5
+              counter=$((counter+1))
+
+              # Verificar si el número de intentos ha alcanzado el límite
+              if [ $counter -ge $max_retries ]; then
+                echo "Se alcanzó el número máximo de intentos. Abortando."
+                exit 1
+              fi
             done
             docker save -o /home/mome/galileo-images-v1.1.0/servicio-unidades_1.1.0.tar galileo/servicio-unidades:1.1.0'
             exit
